<?php

declare(strict_types=1);

namespace App\Controller\Api;

use App\Controller\Api\Trait\ApiResponseTrait;
use BetterAuth\Core\Entities\User;
use BetterAuth\Providers\DeviceManagementProvider\SessionManagerProvider;
use BetterAuth\Symfony\Security\Attribute\CurrentUser;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;

/**
 * Device Controller.
 *
 * Handles device management, tracking, and security.
 * Generated by BetterAuth - customize as needed.
 */
#[Route('/auth/devices', name: 'api_auth_devices_')]
class DeviceController extends AbstractController
{
    use ApiResponseTrait;

    public function __construct(
        private readonly SessionManagerProvider $sessionManager,
        private readonly ?LoggerInterface $logger = null,
    ) {
    }

    /**
     * List all devices/sessions for current user.
     *
     * GET /auth/devices
     * Header: Authorization: Bearer <token>
     */
    #[Route('', name: 'list', methods: ['GET'])]
    public function list(#[CurrentUser] User $user, Request $request): JsonResponse
    {
        try {
            $devices = $this->sessionManager->getUserDevices($user->getId());
            $currentToken = $this->getCurrentToken($request);

            $deviceList = array_map(fn($device) => [
                'id' => $device->getId(),
                'deviceName' => $device->getDeviceName(),
                'deviceType' => $device->getDeviceType(),
                'browser' => $device->getBrowser(),
                'os' => $device->getOperatingSystem(),
                'ipAddress' => $device->getIpAddress(),
                'location' => $device->getLocation(),
                'lastActiveAt' => $device->getLastActiveAt()?->format('c'),
                'createdAt' => $device->getCreatedAt()?->format('c'),
                'isCurrent' => $device->getSessionToken() === $currentToken,
                'trusted' => $device->isTrusted(),
            ], $devices);

            return $this->json([
                'success' => true,
                'data' => [
                    'devices' => $deviceList,
                    'count' => count($deviceList),
                ],
                'meta' => ['timestamp' => date('c'), 'version' => 'v1'],
            ]);
        } catch (\Exception $e) {
            $this->logger?->error('Failed to list devices', [
                'userId' => $user->getId(),
                'error' => $e->getMessage(),
            ]);

            return $this->json(
                $this->formatErrorResponse('list_failed', 'Failed to retrieve devices', 500),
                500
            );
        }
    }

    /**
     * Get details of a specific device.
     *
     * GET /auth/devices/{deviceId}
     * Header: Authorization: Bearer <token>
     */
    #[Route('/{deviceId}', name: 'get', methods: ['GET'])]
    public function get(string $deviceId, #[CurrentUser] User $user): JsonResponse
    {
        try {
            $device = $this->sessionManager->getDevice($deviceId, $user->getId());

            if (!$device) {
                return $this->json(
                    $this->formatErrorResponse('not_found', 'Device not found', 404),
                    404
                );
            }

            return $this->json([
                'success' => true,
                'data' => [
                    'device' => [
                        'id' => $device->getId(),
                        'deviceName' => $device->getDeviceName(),
                        'deviceType' => $device->getDeviceType(),
                        'browser' => $device->getBrowser(),
                        'browserVersion' => $device->getBrowserVersion(),
                        'os' => $device->getOperatingSystem(),
                        'osVersion' => $device->getOsVersion(),
                        'ipAddress' => $device->getIpAddress(),
                        'location' => $device->getLocation(),
                        'fingerprint' => $device->getFingerprint(),
                        'lastActiveAt' => $device->getLastActiveAt()?->format('c'),
                        'createdAt' => $device->getCreatedAt()?->format('c'),
                        'trusted' => $device->isTrusted(),
                        'trustedAt' => $device->getTrustedAt()?->format('c'),
                    ],
                ],
                'meta' => ['timestamp' => date('c'), 'version' => 'v1'],
            ]);
        } catch (\Exception $e) {
            return $this->json(
                $this->formatErrorResponse('not_found', 'Device not found', 404),
                404
            );
        }
    }

    /**
     * Revoke/disconnect a device session.
     *
     * DELETE /auth/devices/{deviceId}
     * Header: Authorization: Bearer <token>
     */
    #[Route('/{deviceId}', name: 'revoke', methods: ['DELETE'])]
    public function revoke(string $deviceId, #[CurrentUser] User $user, Request $request): JsonResponse
    {
        try {
            $device = $this->sessionManager->getDevice($deviceId, $user->getId());

            if (!$device) {
                return $this->json(
                    $this->formatErrorResponse('not_found', 'Device not found', 404),
                    404
                );
            }

            // Prevent revoking current device unless explicitly requested
            $currentToken = $this->getCurrentToken($request);
            if ($device->getSessionToken() === $currentToken) {
                $data = $request->toArray();
                if (!($data['confirmCurrent'] ?? false)) {
                    return $this->json(
                        $this->formatErrorResponse(
                            'current_device',
                            'Cannot revoke current device. Use confirmCurrent: true or logout endpoint.',
                            400
                        ),
                        400
                    );
                }
            }

            $this->sessionManager->revokeDevice($deviceId, $user->getId());

            $this->logger?->info('Device revoked', [
                'userId' => $user->getId(),
                'deviceId' => $deviceId,
            ]);

            return $this->json($this->formatSuccessResponse(
                'Device session revoked',
                ['deviceId' => $deviceId, 'revoked' => true]
            ));
        } catch (\Exception $e) {
            $this->logger?->error('Device revocation failed', [
                'userId' => $user->getId(),
                'deviceId' => $deviceId,
                'error' => $e->getMessage(),
            ]);

            return $this->json(
                $this->formatErrorResponse('revoke_failed', 'Failed to revoke device', 500),
                500
            );
        }
    }

    /**
     * Trust a device (skip 2FA for this device).
     *
     * POST /auth/devices/{deviceId}/trust
     * Header: Authorization: Bearer <token>
     * Body: { "duration": 30 } (days to trust, optional)
     */
    #[Route('/{deviceId}/trust', name: 'trust', methods: ['POST'])]
    public function trust(string $deviceId, #[CurrentUser] User $user, Request $request): JsonResponse
    {
        $data = $request->toArray();
        $duration = min(90, max(1, (int)($data['duration'] ?? 30))); // 1-90 days

        try {
            $device = $this->sessionManager->getDevice($deviceId, $user->getId());

            if (!$device) {
                return $this->json(
                    $this->formatErrorResponse('not_found', 'Device not found', 404),
                    404
                );
            }

            $this->sessionManager->trustDevice($deviceId, $user->getId(), $duration);

            $this->logger?->info('Device trusted', [
                'userId' => $user->getId(),
                'deviceId' => $deviceId,
                'duration' => $duration,
            ]);

            return $this->json($this->formatSuccessResponse(
                'Device marked as trusted',
                [
                    'deviceId' => $deviceId,
                    'trusted' => true,
                    'trustedUntil' => date('c', strtotime("+{$duration} days")),
                ]
            ));
        } catch (\Exception $e) {
            return $this->json(
                $this->formatErrorResponse('trust_failed', 'Failed to trust device', 500),
                500
            );
        }
    }

    /**
     * Remove trust from a device.
     *
     * DELETE /auth/devices/{deviceId}/trust
     * Header: Authorization: Bearer <token>
     */
    #[Route('/{deviceId}/trust', name: 'untrust', methods: ['DELETE'])]
    public function untrust(string $deviceId, #[CurrentUser] User $user): JsonResponse
    {
        try {
            $device = $this->sessionManager->getDevice($deviceId, $user->getId());

            if (!$device) {
                return $this->json(
                    $this->formatErrorResponse('not_found', 'Device not found', 404),
                    404
                );
            }

            $this->sessionManager->untrustDevice($deviceId, $user->getId());

            $this->logger?->info('Device untrusted', [
                'userId' => $user->getId(),
                'deviceId' => $deviceId,
            ]);

            return $this->json($this->formatSuccessResponse(
                'Device trust removed',
                ['deviceId' => $deviceId, 'trusted' => false]
            ));
        } catch (\Exception $e) {
            return $this->json(
                $this->formatErrorResponse('untrust_failed', 'Failed to remove device trust', 500),
                500
            );
        }
    }

    /**
     * Revoke all devices except current.
     *
     * POST /auth/devices/revoke-all
     * Header: Authorization: Bearer <token>
     */
    #[Route('/revoke-all', name: 'revoke_all', methods: ['POST'], priority: 10)]
    public function revokeAll(#[CurrentUser] User $user, Request $request): JsonResponse
    {
        try {
            $currentToken = $this->getCurrentToken($request);
            $count = $this->sessionManager->revokeAllExcept($user->getId(), $currentToken);

            $this->logger?->info('All devices revoked', [
                'userId' => $user->getId(),
                'revokedCount' => $count,
            ]);

            return $this->json($this->formatSuccessResponse(
                'All other device sessions revoked',
                ['revokedCount' => $count]
            ));
        } catch (\Exception $e) {
            $this->logger?->error('Revoke all devices failed', [
                'userId' => $user->getId(),
                'error' => $e->getMessage(),
            ]);

            return $this->json(
                $this->formatErrorResponse('revoke_failed', 'Failed to revoke devices', 500),
                500
            );
        }
    }

    /**
     * Get the current session token from the request.
     */
    private function getCurrentToken(Request $request): ?string
    {
        $authHeader = $request->headers->get('Authorization');
        if ($authHeader && str_starts_with($authHeader, 'Bearer ')) {
            return substr($authHeader, 7);
        }
        return null;
    }
}

