<?php

declare(strict_types=1);

namespace App\Controller\Api;

use App\Controller\Api\Trait\ApiResponseTrait;
use BetterAuth\Core\Entities\User;
use BetterAuth\Providers\EmailVerificationProvider\EmailVerificationProvider;
use BetterAuth\Symfony\Security\Attribute\CurrentUser;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;

/**
 * Email Verification Controller.
 *
 * Handles email verification flow.
 * Generated by BetterAuth - customize as needed.
 */
#[Route('/auth/email', name: 'api_auth_email_')]
class EmailVerificationController extends AbstractController
{
    use ApiResponseTrait;

    public function __construct(
        private readonly EmailVerificationProvider $emailVerificationProvider,
        private readonly ?LoggerInterface $logger = null,
        #[Autowire(env: 'FRONTEND_URL')]
        private readonly string $frontendUrl = 'http://localhost:3000',
    ) {
    }

    /**
     * Send verification email.
     *
     * POST /auth/email/send-verification
     * Header: Authorization: Bearer <token>
     */
    #[Route('/send-verification', name: 'send', methods: ['POST'])]
    public function sendVerification(#[CurrentUser] User $user, Request $request): JsonResponse
    {
        if ($user->isEmailVerified()) {
            return $this->json($this->formatSuccessResponse(
                'Email is already verified',
                ['verified' => true]
            ));
        }

        $data = $request->toArray();
        $callbackUrl = $data['callbackUrl'] ?? rtrim($this->frontendUrl, '/') . '/auth/verify-email';

        try {
            $this->emailVerificationProvider->sendVerificationEmail($user->getId(), $callbackUrl);

            $this->logger?->info('Verification email sent', [
                'userId' => $user->getId(),
                'email' => $user->getEmail(),
            ]);

            return $this->json($this->formatSuccessResponse(
                'Verification email has been sent',
                ['emailSent' => true]
            ));
        } catch (\Exception $e) {
            $this->logger?->error('Failed to send verification email', [
                'userId' => $user->getId(),
                'error' => $e->getMessage(),
            ]);

            return $this->json(
                $this->formatErrorResponse('send_failed', 'Failed to send verification email', 500),
                500
            );
        }
    }

    /**
     * Verify email with token.
     *
     * POST /auth/email/verify
     * Body: { "token": "..." }
     */
    #[Route('/verify', name: 'verify', methods: ['POST'])]
    public function verify(Request $request): JsonResponse
    {
        $data = $request->toArray();

        if (empty($data['token'])) {
            return $this->json(
                $this->formatErrorResponse('validation_error', 'Verification token is required', 422),
                422
            );
        }

        try {
            $result = $this->emailVerificationProvider->verifyEmail($data['token']);

            if (!$result['success']) {
                return $this->json(
                    $this->formatErrorResponse('verification_failed', $result['error'] ?? 'Invalid or expired token', 400),
                    400
                );
            }

            $this->logger?->info('Email verified successfully', [
                'userId' => $result['user_id'] ?? null,
            ]);

            return $this->json($this->formatSuccessResponse(
                'Email has been verified successfully',
                ['verified' => true]
            ));
        } catch (\Exception $e) {
            $this->logger?->error('Email verification failed', [
                'error' => $e->getMessage(),
            ]);

            return $this->json(
                $this->formatErrorResponse('verification_failed', 'Invalid or expired verification token', 400),
                400
            );
        }
    }

    /**
     * Resend verification email.
     *
     * POST /auth/email/resend
     * Body: { "email": "..." }
     */
    #[Route('/resend', name: 'resend', methods: ['POST'])]
    public function resend(Request $request): JsonResponse
    {
        $data = $request->toArray();

        if (empty($data['email'])) {
            return $this->json(
                $this->formatErrorResponse('validation_error', 'Email is required', 422),
                422
            );
        }

        $callbackUrl = $data['callbackUrl'] ?? rtrim($this->frontendUrl, '/') . '/auth/verify-email';

        try {
            $this->emailVerificationProvider->resendVerificationEmail($data['email'], $callbackUrl);

            // Always return success to prevent email enumeration
            return $this->json($this->formatSuccessResponse(
                'If the email exists and is not verified, a verification link has been sent',
                ['emailSent' => true]
            ));
        } catch (\Exception $e) {
            // Still return success to prevent enumeration
            return $this->json($this->formatSuccessResponse(
                'If the email exists and is not verified, a verification link has been sent',
                ['emailSent' => true]
            ));
        }
    }

    /**
     * Check email verification status.
     *
     * GET /auth/email/status
     * Header: Authorization: Bearer <token>
     */
    #[Route('/status', name: 'status', methods: ['GET'])]
    public function status(#[CurrentUser] User $user): JsonResponse
    {
        return $this->json([
            'success' => true,
            'data' => [
                'email' => $user->getEmail(),
                'verified' => $user->isEmailVerified(),
                'verifiedAt' => $user->getEmailVerifiedAt()?->format('c'),
            ],
            'meta' => ['timestamp' => date('c'), 'version' => 'v1'],
        ]);
    }
}

