<?php

declare(strict_types=1);

namespace App\Controller\Api;

use App\Controller\Api\Trait\ApiResponseTrait;
use BetterAuth\Core\AuthManager;
use BetterAuth\Providers\GuestSessionProvider\GuestSessionProvider;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;

/**
 * Guest Session Controller.
 *
 * Handles anonymous/guest user sessions with conversion to registered users.
 * Generated by BetterAuth - customize as needed.
 */
#[Route('/auth/guest', name: 'api_auth_guest_')]
class GuestSessionController extends AbstractController
{
    use ApiResponseTrait;

    public function __construct(
        private readonly GuestSessionProvider $guestSessionProvider,
        private readonly AuthManager $authManager,
        private readonly ?LoggerInterface $logger = null,
    ) {
    }

    /**
     * Create a guest session.
     *
     * POST /auth/guest/create
     * Body: { "deviceId": "..." } (optional)
     */
    #[Route('/create', name: 'create', methods: ['POST'])]
    public function create(Request $request): JsonResponse
    {
        $data = $request->toArray();

        try {
            $result = $this->guestSessionProvider->createGuestSession([
                'device_id' => $data['deviceId'] ?? null,
                'ip_address' => $request->getClientIp() ?? '127.0.0.1',
                'user_agent' => $request->headers->get('User-Agent') ?? 'Unknown',
                'metadata' => $data['metadata'] ?? [],
            ]);

            $this->logger?->info('Guest session created', [
                'guestId' => $result['guest_id'],
            ]);

            return $this->json([
                'success' => true,
                'data' => [
                    'guest' => [
                        'id' => $result['guest_id'],
                        'token' => $result['token'],
                        'expiresAt' => date('c', time() + ($result['expires_in'] ?? 86400)),
                    ],
                ],
                'meta' => ['timestamp' => date('c'), 'version' => 'v1'],
            ], 201);
        } catch (\Exception $e) {
            $this->logger?->error('Failed to create guest session', [
                'error' => $e->getMessage(),
            ]);

            return $this->json(
                $this->formatErrorResponse('creation_failed', 'Failed to create guest session', 500),
                500
            );
        }
    }

    /**
     * Convert guest session to registered user.
     *
     * POST /auth/guest/convert
     * Body: { "guestToken": "...", "email": "...", "password": "...", "name": "..." }
     */
    #[Route('/convert', name: 'convert', methods: ['POST'])]
    public function convert(Request $request): JsonResponse
    {
        $data = $request->toArray();

        // Validation
        $errors = [];
        if (empty($data['guestToken'])) {
            $errors['guestToken'] = 'Guest token is required';
        }
        if (empty($data['email'])) {
            $errors['email'] = 'Email is required';
        } elseif (!filter_var($data['email'], FILTER_VALIDATE_EMAIL)) {
            $errors['email'] = 'Invalid email format';
        }
        if (empty($data['password'])) {
            $errors['password'] = 'Password is required';
        } elseif (strlen($data['password']) < 8) {
            $errors['password'] = 'Password must be at least 8 characters';
        }

        if (!empty($errors)) {
            return $this->json(
                $this->formatErrorResponse('validation_error', 'Invalid input data', 422, $errors),
                422
            );
        }

        try {
            // Verify guest session
            $guestData = $this->guestSessionProvider->getGuestData($data['guestToken']);
            if (!$guestData) {
                return $this->json(
                    $this->formatErrorResponse('invalid_guest', 'Invalid or expired guest session', 401),
                    401
                );
            }

            // Register user
            $user = $this->authManager->signUp(
                email: $data['email'],
                password: $data['password'],
                additionalData: [
                    'name' => $data['name'] ?? null,
                    'metadata' => array_merge(
                        $guestData['metadata'] ?? [],
                        ['converted_from_guest' => $guestData['guest_id']]
                    ),
                ],
            );

            // Transfer guest data to user
            $this->guestSessionProvider->transferGuestData($data['guestToken'], $user->getId());

            // Sign in user
            $loginResult = $this->authManager->signIn(
                email: $data['email'],
                password: $data['password'],
                ipAddress: $request->getClientIp() ?? '127.0.0.1',
                userAgent: $request->headers->get('User-Agent') ?? 'Unknown',
            );

            $this->logger?->info('Guest converted to user', [
                'guestId' => $guestData['guest_id'],
                'userId' => $user->getId(),
            ]);

            return $this->json($this->formatAuthResponse($loginResult, $user, [
                'convertedFromGuest' => true,
                'previousGuestId' => $guestData['guest_id'],
            ]), 201);
        } catch (\Exception $e) {
            $this->logger?->error('Guest conversion failed', [
                'error' => $e->getMessage(),
            ]);

            return $this->json(
                $this->formatErrorResponse('conversion_failed', $e->getMessage(), 400),
                400
            );
        }
    }

    /**
     * Get guest session data.
     *
     * GET /auth/guest/{token}
     */
    #[Route('/{token}', name: 'get', methods: ['GET'])]
    public function get(string $token): JsonResponse
    {
        try {
            $guestData = $this->guestSessionProvider->getGuestData($token);

            if (!$guestData) {
                return $this->json(
                    $this->formatErrorResponse('not_found', 'Guest session not found', 404),
                    404
                );
            }

            return $this->json([
                'success' => true,
                'data' => [
                    'guest' => [
                        'id' => $guestData['guest_id'],
                        'createdAt' => $guestData['created_at'] ?? null,
                        'expiresAt' => $guestData['expires_at'] ?? null,
                        'metadata' => $guestData['metadata'] ?? [],
                    ],
                ],
                'meta' => ['timestamp' => date('c'), 'version' => 'v1'],
            ]);
        } catch (\Exception $e) {
            return $this->json(
                $this->formatErrorResponse('not_found', 'Guest session not found', 404),
                404
            );
        }
    }

    /**
     * Update guest session metadata.
     *
     * PATCH /auth/guest/{token}
     * Body: { "metadata": { ... } }
     */
    #[Route('/{token}', name: 'update', methods: ['PATCH'])]
    public function update(string $token, Request $request): JsonResponse
    {
        $data = $request->toArray();

        try {
            $updated = $this->guestSessionProvider->updateGuestData($token, [
                'metadata' => $data['metadata'] ?? [],
            ]);

            if (!$updated) {
                return $this->json(
                    $this->formatErrorResponse('not_found', 'Guest session not found', 404),
                    404
                );
            }

            return $this->json($this->formatSuccessResponse(
                'Guest session updated',
                ['updated' => true]
            ));
        } catch (\Exception $e) {
            return $this->json(
                $this->formatErrorResponse('update_failed', 'Failed to update guest session', 500),
                500
            );
        }
    }
}

