<?php

declare(strict_types=1);

namespace App\Controller;

use App\Controller\Trait\ApiResponseTrait;
use BetterAuth\Core\AuthManager;
use BetterAuth\Providers\OAuthProvider\OAuthManager;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;

/**
 * OAuth Controller.
 *
 * Handles OAuth authentication (Google, GitHub, Facebook, etc.).
 * Generated by BetterAuth - customize as needed.
 */
#[Route('/auth/oauth', name: 'api_auth_oauth_')]
class OAuthController extends AbstractController
{
    use ApiResponseTrait;

    public function __construct(
        private readonly AuthManager $authManager,
        private readonly OAuthManager $oauthManager,
        private readonly ?LoggerInterface $logger = null,
    ) {
    }

    /**
     * Get OAuth authorization URL or redirect to provider.
     *
     * GET /auth/oauth/{provider}
     * Query: ?redirect=true (optional, to redirect instead of returning URL)
     */
    #[Route('/{provider}', name: 'redirect', methods: ['GET'])]
    public function redirect(string $provider, Request $request): JsonResponse|RedirectResponse
    {
        $supportedProviders = ['google', 'github', 'facebook', 'microsoft', 'discord', 'apple', 'twitter'];

        if (!in_array($provider, $supportedProviders, true)) {
            return $this->json(
                $this->formatErrorResponse('invalid_provider', 'Unsupported OAuth provider: ' . $provider, 400),
                400
            );
        }

        try {
            $state = bin2hex(random_bytes(16));
            $authUrl = $this->oauthManager->getAuthorizationUrl($provider, $state);

            // Store state in session for CSRF protection
            $request->getSession()->set('oauth_state', $state);
            $request->getSession()->set('oauth_provider', $provider);

            // If redirect=true, redirect directly to provider
            if ($request->query->getBoolean('redirect')) {
                return new RedirectResponse($authUrl);
            }

            return $this->json([
                'success' => true,
                'data' => [
                    'provider' => $provider,
                    'authorizationUrl' => $authUrl,
                    'state' => $state,
                ],
                'meta' => ['timestamp' => date('c'), 'version' => 'v1'],
            ]);
        } catch (\Exception $e) {
            $this->logger?->error('OAuth redirect failed', [
                'provider' => $provider,
                'error' => $e->getMessage(),
            ]);

            return $this->json(
                $this->formatErrorResponse('oauth_error', 'Failed to initiate OAuth flow', 500),
                500
            );
        }
    }

    /**
     * Handle OAuth callback from provider.
     *
     * GET /auth/oauth/{provider}/callback
     * Query: ?code=...&state=...
     */
    #[Route('/{provider}/callback', name: 'callback', methods: ['GET'])]
    public function callback(string $provider, Request $request): JsonResponse|RedirectResponse
    {
        $code = $request->query->get('code');
        $state = $request->query->get('state');
        $error = $request->query->get('error');
        $errorDescription = $request->query->get('error_description');

        // Handle OAuth errors
        if ($error) {
            $this->logger?->warning('OAuth error from provider', [
                'provider' => $provider,
                'error' => $error,
                'description' => $errorDescription,
            ]);

            return $this->json(
                $this->formatErrorResponse('oauth_denied', $errorDescription ?? 'OAuth authorization was denied', 400),
                400
            );
        }

        if (!$code) {
            return $this->json(
                $this->formatErrorResponse('missing_code', 'Authorization code is required', 400),
                400
            );
        }

        // Verify state for CSRF protection
        $storedState = $request->getSession()->get('oauth_state');
        if (!$storedState || $storedState !== $state) {
            return $this->json(
                $this->formatErrorResponse('invalid_state', 'Invalid OAuth state - possible CSRF attack', 400),
                400
            );
        }

        try {
            // Exchange code for tokens and get user info
            $result = $this->oauthManager->handleCallback($provider, $code, [
                'ip_address' => $request->getClientIp() ?? '127.0.0.1',
                'user_agent' => $request->headers->get('User-Agent') ?? 'Unknown',
            ]);

            $user = $result['user'];

            $this->logger?->info('OAuth login successful', [
                'provider' => $provider,
                'userId' => $user->getId(),
                'email' => $user->getEmail(),
                'isNewUser' => $result['is_new_user'] ?? false,
            ]);

            // Clear OAuth session data
            $request->getSession()->remove('oauth_state');
            $request->getSession()->remove('oauth_provider');

            return $this->json($this->formatAuthResponse($result, $user, [
                'provider' => $provider,
                'isNewUser' => $result['is_new_user'] ?? false,
            ]));
        } catch (\Exception $e) {
            $this->logger?->error('OAuth callback failed', [
                'provider' => $provider,
                'error' => $e->getMessage(),
            ]);

            return $this->json(
                $this->formatErrorResponse('oauth_failed', 'Failed to complete OAuth authentication', 500),
                500
            );
        }
    }

    /**
     * List supported OAuth providers.
     *
     * GET /auth/oauth
     */
    #[Route('', name: 'list', methods: ['GET'])]
    public function listProviders(): JsonResponse
    {
        $providers = $this->oauthManager->getAvailableProviders();

        return $this->json([
            'success' => true,
            'data' => [
                'providers' => $providers,
            ],
            'meta' => ['timestamp' => date('c'), 'version' => 'v1'],
        ]);
    }
}

