<?php

declare(strict_types=1);

namespace BetterAuth\Core\Interfaces;

use BetterAuth\Core\Entities\AccountLink;

/**
 * Repository interface for Account Link storage.
 */
interface AccountLinkRepositoryInterface
{
    /**
     * Generate a new unique ID for an account link.
     *
     * This method is used by the repository to generate IDs compatible
     * with the underlying storage (UUID v7 or auto-increment INT).
     *
     * @return string|null Generated ID or null if auto-generated by storage
     */
    public function generateId(): ?string;

    /**
     * Create a new account link.
     *
     * @param array<string, mixed> $data Account link data
     *
     * @return AccountLink Created account link
     */
    public function create(array $data): AccountLink;

    /**
     * Find an account link by ID.
     *
     * @param string $id Account link ID
     *
     * @return AccountLink|null Account link or null if not found
     */
    public function findById(string $id): ?AccountLink;

    /**
     * Find all account links for a user.
     *
     * @param string $userId User ID
     *
     * @return array<AccountLink> Array of account links
     */
    public function findByUserId(string $userId): array;

    /**
     * Find an account link by provider and provider ID.
     *
     * @param string $provider Provider name (e.g., 'google', 'github')
     * @param string $providerId Provider ID
     *
     * @return AccountLink|null Account link or null if not found
     */
    public function findByProvider(string $provider, string $providerId): ?AccountLink;

    /**
     * Find an account link for a specific user and provider.
     *
     * @param string $userId User ID
     * @param string $provider Provider name
     *
     * @return AccountLink|null Account link or null if not found
     */
    public function findByUserAndProvider(string $userId, string $provider): ?AccountLink;

    /**
     * Get the primary account link for a user.
     *
     * @param string $userId User ID
     *
     * @return AccountLink|null Primary account link or null
     */
    public function getPrimaryLink(string $userId): ?AccountLink;

    /**
     * Set a specific account link as primary for a user.
     * Unsets all other links for this user as primary.
     *
     * @param string $userId User ID
     * @param string $provider Provider name
     *
     * @return bool True if updated successfully
     */
    public function setPrimary(string $userId, string $provider): bool;

    /**
     * Update an account link.
     *
     * @param string $id Account link ID
     * @param array<string, mixed> $data Data to update
     *
     * @return bool True if updated successfully
     */
    public function update(string $id, array $data): bool;

    /**
     * Delete an account link.
     *
     * @param string $id Account link ID
     *
     * @return bool True if deleted successfully
     */
    public function delete(string $id): bool;

    /**
     * Delete all account links for a user.
     *
     * @param string $userId User ID
     *
     * @return int Number of account links deleted
     */
    public function deleteAllForUser(string $userId): int;

    /**
     * Count account links for a user.
     *
     * @param string $userId User ID
     *
     * @return int Number of account links
     */
    public function countForUser(string $userId): int;

    /**
     * Check if a provider is already linked to a user.
     *
     * @param string $userId User ID
     * @param string $provider Provider name
     *
     * @return bool True if already linked
     */
    public function isLinked(string $userId, string $provider): bool;
}
